/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectlibrary.GUI;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projectlibrary.database.dbBacklog;

/**
 *
 * @author Sae
 */
public class Backlog extends SuperMenu {
    DefaultTableModel dm;
    dbBacklog back = new dbBacklog();
    
    public Backlog(String id,String status) {

        initComponents();
        this.status = status;
        this.id = id;
        jPanel1.setVisible(false);
    }
    
     private void createColumns(){
        dm = (DefaultTableModel) backlogtable.getModel();
        dm.addColumn("ISBN");
        dm.addColumn("Book Name");
        dm.addColumn("Burrow Date");
        dm.addColumn("Return Date");
    }
    
    private void poppulate(String isbn, String bookname, String burrowd, String returnd){
        String[] rowdata = {isbn,bookname,burrowd,returnd};
        dm.addRow(rowdata);  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backlog = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        backlogtable = new javax.swing.JTable();
        main = new javax.swing.JButton();
        show = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Backlog");
        setResizable(false);

        backlog.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        backlog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectlibrary/GUI/img/Backlog.png"))); // NOI18N

        backlogtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(backlogtable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        main.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        main.setText("Main Menu");
        main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainActionPerformed(evt);
            }
        });

        show.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        show.setText("Show Backlog");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(main))
            .addComponent(backlog)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(show)
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backlog)
                .addGap(29, 29, 29)
                .addComponent(show)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainActionPerformed
        dispose();
        if(status.equals("Member")){
            createMenuMember(status, id);
        }
        else{
            createMenuAdmin(status, id);
        }
    }//GEN-LAST:event_mainActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        ArrayList<HashMap> list = back.checkID(id); 

        jPanel1.setVisible(true);
        if(list.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Sorry, don't have this ID in system");
        }
        else{
            for(HashMap l : list){
                poppulate(l.get("ISBN").toString(), l.get("Title").toString(), l.get("BurrowDate").toString(),l.get("ReturnDate").toString());
                /**backlogtable.setValueAt(l.get("BookName"), 0, 0);
                backlogtable.setValueAt(l.get("ISBN"), 0, 1);
                backlogtable.setValueAt(l.get("BurrowDate"), 0, 2);
                backlogtable.setValueAt(l.get("ReturnDate"), 0, 3);     */   
            }
        }
        dbBacklog.disconnect();
    }//GEN-LAST:event_showActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backlog;
    private javax.swing.JTable backlogtable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton main;
    private javax.swing.JButton show;
    // End of variables declaration//GEN-END:variables
}
