/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectlibrary.GUI;


import java.util.ArrayList;
import java.util.HashMap;
import projectlibrary.database.dbUserInfo;

/**
 *
 * @author user
 */
public class Information extends SuperMenu {
    
    dbUserInfo userin = new dbUserInfo();

    public Information(String id,String status) {
        
        this.id = id;
        this.status = status;
        this.setLocationRelativeTo(null);
	this.setResizable(false);
        initComponents();
        insertInfo(id);
        
        /**CSDbDelegate con = new CSDbDelegate("cs14sitkmutt.me","3306","CSC105_G1","CSC105_G1","CSC105_G1");
        con.connect();
        String sql = "SELECT * FROM LibrayAccount WHERE ID = '"+ id + "'";
        ArrayList<HashMap> list = con.queryRows(sql);
        boolean delSuccess = con.executeQuery(sql);
        for(HashMap l : list){
            if(l.get("ID").equals(id)){
                idtxt.setText("ID : " + l.get("ID")) ;
                nametxt.setText("Name : " + l.get("Name"));
                surname.setText("Surname : " + l.get("Surname"));
                birthday.setText("Birthday : " + l.get("DateOfBirth") + "/" + l.get("MonthBirth") + "/" + l.get("YearBirth"));
                house.setText("House no : " + l.get("HouseDate"));
                village.setText("Village : " + l.get("Village"));
                st.setText("Street : " + l.get("Street"));
                sd.setText("Sub district : " + l.get("Subdistrict"));
                dis.setText("District : " + l.get("District"));
                prov.setText("Province : " + l.get("Province"));
                post.setText("Post Code : " + l.get("PostCode"));
                phone.setText("Phone : " + l.get("PhoneNum")); 
            }
        }*/
    }
    
    @Override
    public void createMenu(String status, String id) {
        if(status.equals("Member")){
            MainMenu member = new MainMenu(id,status);
            member.setVisible(true);
        }
        else{
            MainMenuAdmin mainad = new MainMenuAdmin(id,status);
            mainad.setVisible(true);
        }
    }
    
    public void insertInfo(String id){
        dbUserInfo.dbConnect();
        ArrayList<HashMap> listuser = userin.checkInfo(id);
        for(HashMap l : listuser){
            if(l.get("userID").equals(id)){
                idtxt.setText("ID : " + l.get("userID")) ;
                email.setText("Email : " + l.get("email"));
                nametxt.setText("Name : " + l.get("name"));
                surname.setText("Surname : " + l.get("surname"));
                birthday.setText("Birthday : " + l.get("DateOfBirth") + "/" + l.get("MonthBirth") + "/" + l.get("YearBirth"));
                house.setText("House no : " + l.get("address"));
                village.setText("Village : " + l.get("village"));
                st.setText("Street : " + l.get("street"));
                sd.setText("Sub district : " + l.get("sub_district"));
                dis.setText("District : " + l.get("district"));
                prov.setText("Province : " + l.get("province"));
                post.setText("Post Code : " + l.get("postcode"));
                phone.setText("Phone : " + l.get("phonenum")); 
            }
        }
        dbUserInfo.disconnect();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idtxt = new javax.swing.JLabel();
        nametxt = new javax.swing.JLabel();
        surname = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        birthday = new javax.swing.JLabel();
        house = new javax.swing.JLabel();
        sd = new javax.swing.JLabel();
        village = new javax.swing.JLabel();
        st = new javax.swing.JLabel();
        dis = new javax.swing.JLabel();
        post = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        prov = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        email = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My profile");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        idtxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idtxt.setText("ID :");

        nametxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nametxt.setText("Name :");

        surname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        surname.setText("Surname :");

        jLabel5.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectlibrary/GUI/img/Profile.png"))); // NOI18N

        birthday.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        birthday.setText("Birthday :");

        house.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        house.setText("House no :");

        sd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sd.setText("Sub district :");

        village.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        village.setText("Village :");

        st.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        st.setText("Street :");

        dis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dis.setText("District :");

        post.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        post.setText("Post Code :");

        phone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phone.setText("Phone Number :");

        prov.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prov.setText("Province :");

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        email.setText("Email :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cancel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(post, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(151, 151, 151))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nametxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(idtxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(house, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(village, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(st, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(birthday, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dis, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prov, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(house, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dis, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(village, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(st, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(prov, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(post, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        dispose();
        createMenu(status, id);
    }//GEN-LAST:event_cancelActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birthday;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel dis;
    private javax.swing.JLabel email;
    private javax.swing.JLabel house;
    private javax.swing.JLabel idtxt;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel nametxt;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel post;
    private javax.swing.JLabel prov;
    private javax.swing.JLabel sd;
    private javax.swing.JLabel st;
    private javax.swing.JLabel surname;
    private javax.swing.JLabel village;
    // End of variables declaration//GEN-END:variables
}
