/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectlibrary.GUI;

/**
 *
 * @author Sae
 */
public class MainMenuAdmin extends javax.swing.JFrame {

    String status;
    String id;
    
    public MainMenuAdmin(String id,String status) {
        this.status = status;
        this.id = id;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        library = new javax.swing.JLabel();
        infor = new javax.swing.JButton();
        bs = new javax.swing.JButton();
        bl = new javax.swing.JButton();
        ab = new javax.swing.JButton();
        burrow = new javax.swing.JButton();
        returnsys = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");
        setResizable(false);

        library.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        library.setText("Library System");

        infor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        infor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Information icon.png"))); // NOI18N
        infor.setText("Check Information");
        infor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inforActionPerformed(evt);
            }
        });

        bs.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Book-searching icon.png"))); // NOI18N
        bs.setText("Book Searching");
        bs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsActionPerformed(evt);
            }
        });

        bl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/notepad-icon.png"))); // NOI18N
        bl.setText("Backlog");
        bl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blActionPerformed(evt);
            }
        });

        ab.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-book-icon.png"))); // NOI18N
        ab.setText("Add Book");
        ab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abActionPerformed(evt);
            }
        });

        burrow.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        burrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/borrow-icon.png"))); // NOI18N
        burrow.setText("Borrow System");
        burrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burrowActionPerformed(evt);
            }
        });

        returnsys.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        returnsys.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Return-icon.png"))); // NOI18N
        returnsys.setText("Return System");
        returnsys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnsysActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        logout.setText("Log out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(infor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(burrow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ab, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bs)
                    .addComponent(returnsys, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(256, 256, 256))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(library)
                .addGap(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(library)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infor, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bs, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bl, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(ab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(burrow, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnsys, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        dispose();
        Login d = new Login();
        d.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void inforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inforActionPerformed
        dispose();
        Information c = new Information(id,status);
        c.setVisible(true);
    }//GEN-LAST:event_inforActionPerformed

    private void bsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsActionPerformed
        dispose();
        BookSearching b = new BookSearching(id,status);
        b.setVisible(true);
    }//GEN-LAST:event_bsActionPerformed

    private void blActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blActionPerformed
        dispose();
        Backlog bo = new Backlog(id,status);
        bo.setVisible(true);
    }//GEN-LAST:event_blActionPerformed

    private void abActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abActionPerformed
        dispose();
        AddBook Add = new AddBook(id,status);
        Add.setVisible(true);
    }//GEN-LAST:event_abActionPerformed

    private void burrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burrowActionPerformed
        dispose();
        Burrow bu = new Burrow(id,status);
        bu.setVisible(true);
    }//GEN-LAST:event_burrowActionPerformed

    private void returnsysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnsysActionPerformed
        dispose();
        ReturnSystem re = new ReturnSystem(id,status);
        re.setVisible(true);
    }//GEN-LAST:event_returnsysActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ab;
    private javax.swing.JButton bl;
    private javax.swing.JButton bs;
    private javax.swing.JButton burrow;
    private javax.swing.JButton infor;
    private javax.swing.JLabel library;
    private javax.swing.JButton logout;
    private javax.swing.JButton returnsys;
    // End of variables declaration//GEN-END:variables
}
